connector.name=hive
hive.metastore=thrift
hive.metastore.uri=thrift://hive-metastore:9083
hive.non-managed-table-writes-enabled=true
hive.non-managed-table-creates-enabled=true
fs.native-local.enabled=true
local.location=local:///lakehouse
fs.native-s3.enabled=true
s3.region=${ENV:AWS_REGION}
