connector.name=postgresql
connection-url=jdbc:postgresql://${ENV:TRINO_PG_HOST}:${ENV:TRINO_PG_PORT}/${ENV:TRINO_PG_DB}
connection-user=${ENV:TRINO_PG_USER}
connection-password=${ENV:TRINO_PG_PASSWORD}
